server:
  port: 8080
  servlet:
    context-path: /ems
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:com/thymeleaf/mapper/*.xml
  type-aliases-package: com.thymeleaf.entity


logging:
  level:
    root: info
    com.thymeleaf: debug